<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DevelopmentPlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('development_plan')->insert([
            [
                'id' => 1,
                'sort_order' => 10,
                'status' => 'completed',
                'feature_en' => 'REST API development',
                'feature_uk' => 'Розробка REST API',
                'feature_ru' => 'Разработка REST API',
                'technology_en' => 'Laravel, PHP',
                'technology_uk' => 'Laravel, PHP',
                'technology_ru' => 'Laravel, PHP',
                'result_en' => null,
                'result_uk' => null,
                'result_ru' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'sort_order' => 20,
                'status' => 'completed',
                'feature_en' => 'Swagger integration',
                'feature_uk' => 'Інтеграція swagger',
                'feature_ru' => 'Интеграция swagger',
                'technology_en' => 'Laravel, PHP',
                'technology_uk' => 'Laravel, PHP',
                'technology_ru' => 'Laravel, PHP',
                'result_en' => null,
                'result_uk' => null,
                'result_ru' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'sort_order' => 30,
                'status' => 'completed',
                'feature_en' => 'User registration',
                'feature_uk' => 'Реєстрація нових користувачів',
                'feature_ru' => 'Регистрация новых пользователей',
                'technology_en' => 'Laravel, PHP',
                'technology_uk' => 'Laravel, PHP',
                'technology_ru' => 'Laravel, PHP',
                'result_en' => null,
                'result_uk' => null,
                'result_ru' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'sort_order' => 40,
                'status' => 'completed',
                'feature_en' => 'Email confirmation after registration',
                'feature_uk' => 'Підтвердження реєстрації по email',
                'feature_ru' => 'Подтверждение регистрации по email',
                'technology_en' => 'Laravel, PHP',
                'technology_uk' => 'Laravel, PHP',
                'technology_ru' => 'Laravel, PHP',
                'result_en' => null,
                'result_uk' => null,
                'result_ru' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'sort_order' => 50,
                'status' => 'completed',
                'feature_en' => 'Login for registered users',
                'feature_uk' => 'Вхід для зареєстрованих користувачів',
                'feature_ru' => 'Login зарегистрированных юзеров',
                'technology_en' => 'Laravel, PHP',
                'technology_uk' => 'Laravel, PHP',
                'technology_ru' => 'Laravel, PHP',
                'result_en' => null,
                'result_uk' => null,
                'result_ru' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'sort_order' => 60,
                'status' => 'completed',
                'feature_en' => 'Access for registered users via Bearer',
                'feature_uk' => 'Доступ зареєстрованих користувачів через Bearer',
                'feature_ru' => 'Доступ зарегистрированных юзеров через Baerer',
                'technology_en' => 'Laravel, PHP',
                'technology_uk' => 'Laravel, PHP',
                'technology_ru' => 'Laravel, PHP',
                'result_en' => null,
                'result_uk' => null,
                'result_ru' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'sort_order' => 70,
                'status' => 'completed',
                'feature_en' => 'Role-based access control',
                'feature_uk' => 'Розмежування доступу за ролями',
                'feature_ru' => 'Разграничение доступа по ролям',
                'technology_en' => 'Laravel, PHP',
                'technology_uk' => 'Laravel, PHP',
                'technology_ru' => 'Laravel, PHP',
                'result_en' => null,
                'result_uk' => null,
                'result_ru' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'sort_order' => 80,
                'status' => 'completed',
                'feature_en' => 'Multilanguage support',
                'feature_uk' => 'Підтримка мультимовності',
                'feature_ru' => 'Подержка мультиязычности',
                'technology_en' => 'Laravel, PHP',
                'technology_uk' => 'Laravel, PHP',
                'technology_ru' => 'Laravel, PHP',
                'result_en' => null,
                'result_uk' => null,
                'result_ru' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'sort_order' => 90,
                'status' => 'completed',
                'feature_en' => 'Integration of Twig templating engine and template adaptation',
                'feature_uk' => 'Інтеграція Twig-шаблонізатора та адаптація шаблонів',
                'feature_ru' => 'Интеграция Twig-шаблонизатора и адаптация шаблонов',
                'technology_en' => 'Laravel, PHP',
                'technology_uk' => 'Laravel, PHP',
                'technology_ru' => 'Laravel, PHP',
                'result_en' => null,
                'result_uk' => null,
                'result_ru' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'sort_order' => 100,
                'status' => 'completed',
                'feature_en' => 'Added Custom tools by Artisan',
                'feature_uk' => 'Додано Custom tools у Artisan',
                'feature_ru' => 'Добавлены Custom tools в Artisan',
                'technology_en' => 'Laravel, Artisan, PHP',
                'technology_uk' => 'Laravel, Artisan, PHP',
                'technology_ru' => 'Laravel, Artisan, PHP',
                'result_en' => null,
                'result_uk' => null,
                'result_ru' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'sort_order' => 10,
                'status' => 'in_progress',
                'feature_en' => 'Integration with payment systems',
                'feature_uk' => 'Інтеграція з платіжними системами',
                'feature_ru' => 'Интеграция с платёжными системами',
                'technology_en' => 'LiqPay API, PayPal SDK',
                'technology_uk' => 'LiqPay API, PayPal SDK',
                'technology_ru' => 'LiqPay API, PayPal SDK',
                'result_en' => 'Ability to create and process payments, webhooks',
                'result_uk' => 'Можливість створювати та обробляти платежі, webhooks',
                'result_ru' => 'Возможность создавать и обрабатывать платежи, webhooks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'sort_order' => 10,
                'status' => 'pending',
                'feature_en' => 'Queues and background jobs',
                'feature_uk' => 'Черги та фонові задачі',
                'feature_ru' => 'Очереди и фоновые задачи',
                'technology_en' => 'Laravel-queue, Redis, Supervisor',
                'technology_uk' => 'Laravel-queue, Redis, Supervisor',
                'technology_ru' => 'Laravel-queue, Redis, Supervisor',
                'result_en' => 'Deferred and async jobs (email, reports, webhooks)',
                'result_uk' => 'Відкладені та асинхронні задачі (email, звіти, webhook-и)',
                'result_ru' => 'Отложенные и асинхронные задачи (email, отчёты, webhook-и)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'sort_order' => 20,
                'status' => 'pending',
                'feature_en' => 'User and role management',
                'feature_uk' => 'Управління користувачами та ролями',
                'feature_ru' => 'Управление пользователями и ролями',
                'technology_en' => 'Laravel Gates/Policies, Spatie Roles',
                'technology_uk' => 'Laravel Gates/Policies, Spatie Roles',
                'technology_ru' => 'Laravel Gates/Policies, Spatie Roles',
                'result_en' => 'UI + API for role-based access management',
                'result_uk' => 'UI + API для керування доступом за ролями',
                'result_ru' => 'UI + API для управления доступом по ролям',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'sort_order' => 30,
                'status' => 'pending',
                'feature_en' => 'User activity audit',
                'feature_uk' => 'Аудит дій користувачів',
                'feature_ru' => 'Аудит действий пользователей',
                'technology_en' => 'Spatie ActivityLog, custom AuditBehavior',
                'technology_uk' => 'Spatie ActivityLog, custom AuditBehavior',
                'technology_ru' => 'Spatie ActivityLog, custom AuditBehavior',
                'result_en' => 'Storing user activity history',
                'result_uk' => 'Зберігання історії дій користувачів',
                'result_ru' => 'Хранение истории действий пользователей',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'sort_order' => 40,
                'status' => 'pending',
                'feature_en' => 'Webhooks and external APIs',
                'feature_uk' => 'Вебхуки та зовнішні API',
                'feature_ru' => 'Webhooks и внешние API',
                'technology_en' => 'Guzzle, subscriptions, webhook routes',
                'technology_uk' => 'Guzzle, підписки, webhook routes',
                'technology_ru' => 'Guzzle, подписки, webhook routes',
                'result_en' => 'Receiving/processing events from external services',
                'result_uk' => 'Отримання/обробка подій від зовнішніх сервісів',
                'result_ru' => 'Получение/обработка событий от внешних сервисов',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'sort_order' => 50,
                'status' => 'pending',
                'feature_en' => 'Testing API and business logic',
                'feature_uk' => 'Тестування API та бізнес-логіки',
                'feature_ru' => 'Тестирование API и логики',
                'technology_en' => 'PHPUnit, Pest, Codeception',
                'technology_uk' => 'PHPUnit, Pest, Codeception',
                'technology_ru' => 'PHPUnit, Pest, Codeception',
                'result_en' => 'Test coverage for REST and business logic',
                'result_uk' => 'Покриття тестами REST та бізнес-логіки',
                'result_ru' => 'Покрытие тестами REST и бизнес-логики',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
